import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import {ThemeProvider} from "@/context/ThemeContext";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next js full responsive ',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider>
          <div className="container max-w-[1366px] min-h-[100vh] my-0 mx-auto py-0 px-[60px]
          flex flex-col justify-between">
          <Navbar/>
          {children}
          <Footer/>
          </div>
      </ThemeProvider>
      </body>
    </html>
  )
}
